### ISSUE TITLE
Add link to Details page on map card pop-up

### ISSUE THREAD

**Issue by JessicaInTime** [bcgov/BCHeritage#989] opened 2024-07-05 23:34 UTC
In #666 it's requested to include a way for the user to have a link to the details tab within the map popup.

What needs to be investigated is how/if the frontend would be able to switch the map view to the details tab and with related resource information.

**Comment by emjohnst** [comment] 2024-08-14 19:57
@bferguso Approved initial estimate to investigate how to achieve this. Please provided updated estimate when looked into.

**Comment by emjohnst** [comment] 2024-10-15 21:37
@bferguso this seems to be working seamlessly for most sites - I did find one anomaly: When clicking on City of Ainsworth shipwreck in Test I can see the details page clicking the details page button as a listing in the sidebar, but when going to the map and clicking on the map pop'up card details page the details page is blank.

Also - can we add the details button to the map card for internal users too??

 ![Image](https://github.com/user-attachments/assets/2d3aaff3-f3ed-4d9d-8c92-474c621ea0f8)
![Image](https://github.com/user-attachments/assets/0afd0bd0-057a-4bc5-8804-6fc71b5c70d8)

**Comment by bferguso** [comment] 2024-10-25 00:05
@emjohnst  - Can you please retest? There was a disk space issue last week that may have been the cause of this? I'm able to see that site without issue in TEST. If you're still seeing that behaviour with your browser, please send me the output of your browser console as there will typically be errors there when you see that kind of behaviour.

Also, the link should be there for internal users too. I'm seeing it when logged into test:
![Image](https://github.com/user-attachments/assets/fd1c41c4-a632-4646-9511-269b4c2f81c9)

**Comment by emjohnst** [comment] 2024-10-25 16:31
@bferguso yes this is working now

**Comment by bferguso** [comment] 2024-10-25 18:57
Reopening and moving to Done until this makes it into PROD.

**Comment by emjohnst** [comment] 2024-10-29 16:03
@bferguso When adding a new site, details page from map is blank but details page from sidebar search is complete. See "New Test Site" in Test.

![Image](https://github.com/user-attachments/assets/4528308b-1c5b-4fca-a1c3-a769c15f8ee5)

**Comment by bferguso** [comment] 2024-10-29 22:30
After doing some investigation it seems like this only happens when the details link in the search results cards is used before the link in the Map Popup. The Details card seems to come up properly if the details tab is selected from the map popup first.

This ended up being because the resource tiles are not cached when the resources are loaded into the result list. The map popup was trying to use these cached resources, and without the tiles there was no data to render on the details page.

**Closed as completed** 2024-11-08 19:15 UTC
Labels: enhancement, bcrhp, needs estimate, approved
