### ISSUE TITLE
Identify which attributes need to be included

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#841] opened 2024-02-08 18:59 UTC

**Comment by bferguso** [comment] 2024-04-18 04:27
@emjohnst  - I think this was about hiding some values in the report view. Now that we're limiting to the details page this should be unnecessary. Moving to QA - if you agree, please move to done.

**Comment by emjohnst** [comment] 2024-06-06 16:09
@bferguso yes, or this ticket might be a duplicate of #645 I have attached that ticket to the epic now and will close this ticket.

**Closed as completed by emjohnst** 2024-06-06 16:09 UTC
Labels: bcrhp
